### ISSUE TITLE
Errors while starting up and running homebridge

### ISSUE THREAD

**Issue by Alwiz79** [wylanswets/homebridge-sure-petcare-platform#15]
After restarting HB I get the following error messages in the status view:`

`10/22/2020, 14:07:58] TypeError: Cannot read property 'data' of null
    at SurePetcarePetFlap.pollStatus (/usr/local/lib/node_modules/homebridge-sure-petcare-platform/accessories/SurePetcarePetFlap.js:46:23)
    at /usr/local/lib/node_modules/homebridge-sure-petcare-platform/index.js:66:21
    at /usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:128:56
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:128:33
    at SurePetcareApi.<anonymous> (/usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:179:13)
    at self.callback (/usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:315:20)`

Any ideas what this is about?

**Comment by Alwiz79** [comment]
I rolled back to version 0.1.2, now everything is fine again

**Comment by Alwiz79** [comment]
Also HB is restarting regularly due to SIGTERM.
I had to temporarly uninstall to avoid rebooting all the time...

**Comment by wylanswets** [comment]
Hey @Alwiz79 I have just pushed up 0.1.5 with a few bugfixes including one that should take care of this. It does a null check on poll status which in translation should keep it from crashing. Let me know if that makes it stable... the only potential side-effect to watch for is if devices never update themselves it may mean something else is going on. Let me know if that works.

**Comment by Alwiz79** [comment]
Hi @wylanswets  still not working correctly:

`10/22/2020, 16:15:07] TypeError: Cannot read property 'statusCode' of undefined
    at SurePetcareApi.<anonymous> (/usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/sure_petcare/index.js:51:19)
    at self.callback (/usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-sure-petcare-platform/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)`

**Comment by wylanswets** [comment]
Okay that seems to indicate that the login process did not work.... make sure the password works properly. If that's not working there shouldn't be limitations on the password but perhaps check if there's special characters in your password. Again, it shouldn't cause problems but if so maybe try a password without special characters.

**Comment by wylanswets** [comment]
I've also just uploaded a new version that should be more helpful with error messages to tell you what's wrong.

**Comment by Alwiz79** [comment]
Now I'm getting this error message.

`Login failed.
undefined
Error: connect ETIMEDOUT 52.20.139.208:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '52.20.139.208',
  port: 443
}`

My login credentials are ok, when I log in to the website directly. Not sure if there is problem with the API (timeout)?

**Comment by Alwiz79** [comment]
I changed my password, so that I don't have any special characters in there. 
The error message remains the same - the login seems to be a problem right now.. (?)
`Login failed.
undefined
Error: connect ETIMEDOUT 54.174.117.86:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '54.174.117.86',
  port: 443
}`

**Comment by Alwiz79** [comment]
I'm getting the same error with a plugin for the ioBroker. 
Could it be there were changes on the API? 
Does anybody else experience this problem?

**Comment by Alwiz79** [comment]
The ip adress 54.174.117.86 seems to be an Amazon AWS server..maybe something changed there?

**Comment by Alwiz79** [comment]
Today it seems to work...
