### ISSUE TITLE
Warning: Model must have a length of more than 1 character

### ISSUE THREAD

**Issue by klaptafel** [wylanswets/homebridge-sure-petcare-platform#21]
I get this:

`[10/03/2021, 09:37:10] [homebridge-sure-petcare-platform] This plugin generated a warning from the characteristic 'Model': [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value. See https://git.io/JtMGR for more info.`

**Comment by nickjvturner** [comment]
I am also seeing this:

[Back Door@@Model] [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value

**Comment by cjastennett** [comment]
Me also:

[homebridge-sure-petcare-platform] This plugin generated a warning from the characteristic 'Model': [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value. See https://git.io/JtMGR for more info.

Any chance of a fix for this?

Great plugin by the way - has always worked really well for me, and this is the first warning I have had!

cheers

**Comment by hubert3** [comment]
+1, same issue here

This plugin is currently not compatible with homebridge 1.3.4 due to this error - have to stay on 1.2.5

**Comment by wylanswets** [comment]
Hey guys, sorry for the delay on this - can you all update to the plugin version 0.1.7 and try it again? As @hubert3 said it seems to be the newer version of homebridge that caused the issue, I've been out of developing plugins for a while so I have not kept up with the changes in homebridge very well. Since upgrading homebridge I did encounter the same issue and have added a workaround that resolved the issue for me.

Let me know if you're still having the issue after the update.

Thanks!

**Comment by klaptafel** [comment]
Looks like it's fixed now. Thanks!

**Comment by Sommi486** [comment]
Unfortunately the bug still persists with the current version.

Can anything else be changed in the code?

Many Thanks!!




[21/04/2021, 09:18:31] [homebridge-sure-petcare-platform] This plugin generated a warning from the characteristic 'Model': [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value. See https://git.io/JtMGR for more info.
